sudo: required
dist: bionic

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: change


addons:
  apt:
    packages:
      - jq

################################################################################

stage_base: &stage_base
  before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - export WORKRAVE_FULL_TAG=`git describe --tags --abbrev=10`
    - export WORKRAVE_TAG=`git describe --abbrev=0`
    - export WORKRAVE_COMMIT_COUNT=`git rev-list ${WORKRAVE_TAG}..HEAD --count`
    - export WORKRAVE_COMMIT_HASH=`git rev-parse HEAD`
    - export WORKRAVE_BUILD_DATE=`date +"%Y%m%d"`
    - export WORKRAVE_BUILD_ID="$WORKRAVE_BUILD_DATE-$WORKRAVE_FULL_TAG"
    - export WORKRAVE_UPLOAD_DIR="snapshots/next/$WORKRAVE_BUILD_ID"
    - |
        # Configure MinIO endpoint
        pip install --user awscli
        aws configure set aws_access_key_id travis
        aws configure set aws_secret_access_key $SNAPSHOTS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1
        aws configure set default.s3.signature_version s3v4
        aws configure set s3.endpoint_url https://snapshots.workrave.org/

        if [ ${TRAVIS_OS_NAME} = "osx" ]; then
          # compilation with system wide gettext fails at the link stage with missing symbols...
          brew install gettext qt5 python3
          brew link gettext --force
          brew linkapps qt5
          brew outdated cmake || brew upgrade cmake

          pip3 install --user Jinja2==2.8 # required for dbus support, system (distro) wide include paths are ignored

        elif [ ${TRAVIS_OS_NAME} = "linux" ]; then
          pushd /tmp
          curl -OL https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
          tar xvfj linux-amd64-github-release.tar.bz2
          mkdir -p ~/bin/
          mv bin/linux/amd64/github-release ~/bin/
          chmod +x ~/bin/github-release
          popd
        fi

stage_build_docker: &stage_build_docker
  <<: *stage_base
  os: linux
  dist: bionic
  language: cpp
  script: |
    if [[ $DOCKER_IMAGE ]]; then
      docker run --rm \
          -v "$TRAVIS_BUILD_DIR:/workspace/source" \
          $(printenv | grep -E '^(COMPILER|WITH_UI|CONF_ENABLE|CONF_DISABLE|DOCKER_IMAGE|TRAVIS_.*|WORKRAVE_.*)=' | sed 's/^\(.*\)=\(.*\)/-e\1=\"\2\" /g' \
          rcaelers/workrave-build:${DOCKER_IMAGE} \
          sh -c "/workspace/source/build/travis/build.sh"
    else
       build/travis/build.sh
    fi

stage_build_osx: &stage_build_osx
  <<: *stage_base
  os: osx
  osx_image: xcode11
  language: cpp
  script:
    - build/travis/build.sh

stage_deploy: &stage_deploy
  <<: *stage_base
  deploy:
    - provider: script
      skip_cleanup: true
      on:
        repo: rcaelers/workrave
        branch: next_DISABLED
        tags: true
      script: build/travis/deploy-upload.sh

    - provider: s3
      skip_cleanup: true
      local_dir: _deploy
      upload_dir: "$WORKRAVE_UPLOAD_DIR"
      acl: public_read
      bucket: org-workrave
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      region: eu-central-1
      on:
        repo: rcaelers/workrave
        branch: next
  
    - provider: s3
      skip_cleanup: true
      local_dir: _deploy
      upload_dir: "$WORKRAVE_UPLOAD_DIR"
      acl: public_read
      bucket: org-workrave
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      region: eu-central-1
      on:
        repo: rcaelers/workrave
        tags: true

  after_success:
    - aws s3 --endpoint-url https://snapshots.workrave.org/ cp --recursive _deploy/* s3://"$WORKRAVE_UPLOAD_DIR"

stage_deploy_ppa: &stage_deploy_ppa
  <<: *stage_base
  os: linux
  dist: bionic
  language: cpp
  script: |
    if [[ $DOCKER_IMAGE ]]; then
      docker run --rm \
          -v "$TRAVIS_BUILD_DIR:/workspace/source" \
          -e TRAVIS_TAG=${TRAVIS_TAG} \
          rcaelers/workrave-build:${DOCKER_IMAGE} \
          sh -c "/workspace/source/build/travis/ppa.sh"
    else
       build/travis/ppa.sh
    fi

jobs:
  include:
#    - stage: prepare
#      script: |
#        VERSION=`echo $TRAVIS_TAG | sed -e 's/_/./g'` \
#        github-release release \
#          --user "${TRAVIS_REPO_SLUG%%/[^/]*}" \
#          --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
#          --tag "$TRAVIS_TAG" \
#          --name "Workrave $VERSION" \
#          --description "New release" \
#          --draft
#      <<: *stage_base

    ###########################################################################
    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-xenial"
      <<: *stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-bionic"
      <<: *stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-cosmic"
      <<: *stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-disco"
      <<: *stage_build_docker
      <<: *stage_deploy

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-eoan"
      <<: *stage_build_docker
      <<: *stage_deploy

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-disco-plus"
      <<: *stage_build_docker

    - stage: build
      env: >
        COMPILER="clang"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-disco-plus"
      <<: *stage_build_docker

    - stage: build
      env: >
        COMPILER="clang"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE,TRACING"
        CONF_DISABLE="GCONF,TESTS,COVERAGE"
        DOCKER_IMAGE="ubuntu-disco-plus"
      <<: *stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE=""
        CONF_DISABLE="INDICATOR,GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="mingw-gtk"
      <<: *stage_build_docker
      <<: *stage_deploy

    - stage: build
      compiler: clang
      env: >
        WITH_UI="Qt5"
        CONF_ENABLE=""
        CONF_DISABLE="INDICATOR,GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
      <<: *stage_build_osx

    - stage: release
      language: node_js
      node_js:
        - 12.7.0
      script:
        - cd TRAVIS_BUILD_DIR/build/travis/catalog
        - npm i
        - node --experimental-modules main.js 
      <<: *stage_base

#    - stage: release
#      script:
#        - |
#          VERSION=`echo $TRAVIS_TAG | sed -e 's/_/./g'` \
#          github-release edit \
#          --user "${TRAVIS_REPO_SLUG%%/[^/]*}" \
#          --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
#          --tag "$TRAVIS_TAG" \
#          --name "Workrave $VERSION" \
#          --description "New release"
#      <<: *stage_base
#
#    - stage: ppa
#      env: >
#        DOCKER_IMAGE="ubuntu-bionic"
#      before_install:
#        - mkdir -p _dist/secrets
#        - chmod 0700 _dist/secrets
#        - openssl aes-256-cbc -K $encrypted_cc78bd3121e0_key -iv $encrypted_cc78bd3121e0_iv -in build/travis/secrets.tar.enc -out _dist/secrets/secrets.tar -d
#        - tar xf _dist/secrets/secrets.tar -C _dist/
#        - rm -f _dist/secrets/secrets.tar
#        - echo $GPG_PASSPHRASE > _dist/secrets/priv-key
#      <<: *stage_deploy_ppa

#after_failure:
#  - |
#    github-release delete \
#    --user "${TRAVIS_REPO_SLUG%%/[^/]*}" \
#    --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
#    --tag "$TRAVIS_TAG"

stages:
#    - name: prepare
#      if: tag IS present AND type = push
    - name: build
#    - name: release
#      if: tag IS present AND tag =~ ^v2_.*$ AND type = push
#    - name: ppa
#      if: tag IS present AND tag =~ ^v2_.*$ AND type = push

#  --description "$(cat /tmp/release-note)"
