sudo: required
dist: trusty

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: change

################################################################################

stage_generic: &stage_generic
  before_deploy:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - GIT_TAG=`git describe --tags --abbrev=10`
    - BUILD_DATE=`date +"%Y%m%d"`

stage_generic_build: &stage_generic_build
  <<: *stage_generic
  script: |
    if [[ $DOCKER_IMAGE ]]; then
      docker run --rm \
          -v "$TRAVIS_BUILD_DIR:/workspace/source" \
          $(printenv | grep -E '^(COMPILER|WITH_UI|CONF_ENABLE|CONF_DISABLE|DOCKER_IMAGE|TRAVIS_BUILD_DIR|TRAVIS_TAG)=' | sed 's/^/-e /g') \
          rcaelers/workrave-build:${DOCKER_IMAGE} \
          sh -c "/workspace/source/build/travis/build.sh"
    else
       build/travis/build.sh
    fi

stage_github: &stage_github
  <<: *stage_generic
  os: linux
  dist: trusty
  language: cpp
  before_install:
    |
    if [ ${TRAVIS_OS_NAME} = "linux" ]; then
      pushd /tmp
      curl -OL https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
      tar xvfj linux-amd64-github-release.tar.bz2
      mkdir -p ~/bin/
      mv bin/linux/amd64/github-release ~/bin/
      chmod +x ~/bin/github-release
      popd
    fi

stage_linux: &stage_linux
  <<: *stage_generic_build
  os: linux
  dist: trusty
  language: cpp

stage_win32: &stage_win32
  <<: *stage_linux

stage_deploy: &stage_deploy
  <<: *stage_linux
  <<: *stage_github
  deploy:
#    - provider: script
#      skip_cleanup: true
#      on:
#        repo: rcaelers/workrave
#        branch: next
#        tags: true
#      script: build/travis/deploy-upload.sh

    - provider: s3
      skip_cleanup: true
      local_dir: _deploy
      upload_dir: "snapshots/next/$BUILD_DATE-$GIT_TAG"
      acl: public_read
      bucket: org-workrave
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      region: eu-central-1
      on:
        repo: rcaelers/workrave
        branch: next
  
    - provider: s3
      skip_cleanup: true
      local_dir: _deploy
      upload_dir: "snapshots/next/$BUILD_DATE-$GIT_TAG"
      acl: public_read
      bucket: org-workrave
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      region: eu-central-1
      on:
        repo: rcaelers/workrave
        tags: true

stage_osx: &stage_osx
  <<: *stage_generic_build
  os: osx
  osx_image: xcode9.4
  language: cpp
  before_install:
    |
    if [ ${TRAVIS_OS_NAME} = "osx" ]; then
      # compilation with system wide gettext fails at the link stage with missing symbols...
      brew install gettext qt5 python3
      brew link gettext --force
      brew linkapps qt5
      brew outdated cmake || brew upgrade cmake
      
      pip3 install --user Jinja2==2.8 # required for dbus support, system (distro) wide include paths are ignored
    fi

stage_ppa: &stage_ppa
  <<: *stage_generic
  os: linux
  dist: trusty
  language: cpp
  script: |
    if [[ $DOCKER_IMAGE ]]; then
      docker run --rm \
          -v "$TRAVIS_BUILD_DIR:/workspace/source" \
          -v "/tmp/secrets:/tmp/secrets" \
          -e TRAVIS_TAG=${TRAVIS_TAG} \
          rcaelers/workrave-build:${DOCKER_IMAGE} \
          sh -c "/workspace/source/build/travis/ppa.sh"
    else
       build/travis/ppa.sh
    fi

jobs:
  include:
#    - stage: prepare
#      script: |
#        VERSION=`echo $TRAVIS_TAG | sed -e 's/_/./g'` \
#        github-release release \
#          --user "${TRAVIS_REPO_SLUG%%/[^/]*}" \
#          --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
#          --tag "$TRAVIS_TAG" \
#          --name "Workrave $VERSION" \
#          --description "New release" \
#          --draft
#      <<: *stage_generic
#      <<: *stage_github

    ###########################################################################
    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-xenial"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-artful"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-bionic"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-cosmic"
      <<: *stage_linux
      <<: *stage_deploy

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-disco"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-cosmic-plus"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="clang"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE"
        CONF_DISABLE="GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-cosmic-plus"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="clang"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE,TRACING"
        CONF_DISABLE="GCONF,TESTS,COVERAGE"
        DOCKER_IMAGE="ubuntu-cosmic-plus"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="clang"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GNOME_CLASSIC_PANEL,GSTREAMER,PULSE,TRACING"
        CONF_DISABLE="GCONF,TESTS,COVERAGE"
        DOCKER_IMAGE="ubuntu-cosmic-plus"
      <<: *stage_linux

    - stage: build
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE=""
        CONF_DISABLE="INDICATOR,GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="mingw-gtk"
      <<: *stage_win32
      <<: *stage_deploy

    - stage: build
      compiler: clang
      env: >
        WITH_UI="Qt5"
        CONF_ENABLE=""
        CONF_DISABLE="INDICATOR,GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
      <<: *stage_osx

#    - stage: release
#      script:
#        - |
#          VERSION=`echo $TRAVIS_TAG | sed -e 's/_/./g'` \
#          github-release edit \
#          --user "${TRAVIS_REPO_SLUG%%/[^/]*}" \
#          --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
#          --tag "$TRAVIS_TAG" \
#          --name "Workrave $VERSION" \
#          --description "New release"
#      <<: *stage_generic
#      <<: *stage_github
#
#    - stage: ppa
#      env: >
#        DOCKER_IMAGE="ubuntu-bionic"
#      before_install:
#        - openssl aes-256-cbc -K $encrypted_ad072dc8e07b_key -iv $encrypted_ad072dc8e07b_iv -in build/travis/secring.gpg.enc -out build/travis/secring.gpg -d
#        - chmod 0600 build/travis/secring.gpg
#      <<: *stage_ppa

#after_failure:
#  - |
#    github-release delete \
#    --user "${TRAVIS_REPO_SLUG%%/[^/]*}" \
#    --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
#    --tag "$TRAVIS_TAG"

stages:
#    - name: prepare
#      if: tag IS present AND type = push
    - name: build
#    - name: release
#      if: tag IS present AND tag =~ ^v2_.*$ AND type = push
#    - name: ppa
#      if: tag IS present AND tag =~ ^v2_.*$ AND type = push

#  --description "$(cat /tmp/release-note)"
