# autoconf-archive for Ubuntu 12.04 LTS is too old
# need to use at least Ubuntu 14.04 LTS (trusty) with custom install step
# `apt' travis plugin is not suitable as not all build dependencies are whitelisted
#TODO: allow to build in 12.04 LTS (precise): fix missing C++11 checking macro if it is not required
#TODO: investigate if Ubuntu 14.04 contained support for mate applet or it was added later (--disable-mate for now)

sudo: required
dist: trusty


notifications:
  email: false

language: cpp


# TODO: current configure.ac does not allow to specify gtk2 or gtk3 explicitly
# using CONF_GTK_VER here only to install required libs and thus influence gtk version choice

#
# build matrix
#
env:
  - >
    CONF_GTK_VER=2
    CONF_ENABLE="gconf,gstreamer,exercises"
    CONF_DISABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,manual,experimental"
  - >
    CONF_GTK_VER=2
    CONF_ENABLE="xml,dbus,distribution,pulse,xfce,exercises,manual"
    CONF_DISABLE="gnome3,gconf,gsettings,gstreamer,mate,indicator,experimental"
  - >
    CONF_GTK_VER=2
    CONF_ENABLE="gsettings,pulse,xfce,exercises,manual"
    CONF_DISABLE="gnome3,xml,gconf,gstreamer,dbus,mate,indicator,distribution,experimental"
  - >
    CONF_GTK_VER=3
    CONF_ENABLE="gnome3,gsettings,gstreamer,pulse,exercises"
    CONF_DISABLE="gconf,xml,dbus,indicator,mate,xfce,distribution,manual,experimental"
  - >
    CONF_GTK_VER=3
    CONF_ENABLE="gnome3,gsettings,indicator,xfce,dbus,distribution,gstreamer,pulse,exercises,manual,experimental"
    CONF_DISABLE="gconf,xml,mate"
os:
  - linux
#TODO:  - osx

before_install: |
  conf_opt()
  {
    if [[ $CONF_ENABLE =~ (^|[, ])$1([, ]|$) ]]; then
      echo "--enable-$1";
    else
      if [[ $CONF_DISABLE =~ (^|[, ])$1([, ]|$) ]]; then
        echo "--disable-$1";
      else
        echo "Parameter $1 is not in \$CONF_ENABLE or \$CONF_DISABLE " 1>&2
      fi
    fi
  }
  conf_opt_packages()
  {
    if [[ $CONF_ENABLE =~ (^|[, ])$1([, ]|$) ]]; then
      shift
      echo "$@"
    else
      if [[ !( $CONF_DISABLE =~ (^|[, ])$1([, ]|$) ) ]]; then
        echo "Parameter $1 is not in \$CONF_ENABLE or \$CONF_DISABLE " 1>&2
      fi
    fi
  }

install:
  - pip install --user Cheetah # required for dbus support, system (distro) wide include paths are ignored
  - sudo apt-get update -q
  - |
    sudo apt-get -y -q -V --no-install-recommends install \
      build-essential \
      automake \
      autoconf \
      autoconf-archive \
      libtool \
      autopoint \
      intltool \
      libxtst-dev \
      libxss-dev \
      gobject-introspection \
      `conf_opt_packages xml libgdome2-dev` \
      `conf_opt_packages gconf libgconf2-dev` \
      `[[ $CONF_GTK_VER = 2 ]] && echo libgtk2.0-dev libgtkmm-2.4-dev` \
      `[[ $CONF_GTK_VER = 3 ]] && echo libgtk-3-dev libgtkmm-3.0-dev` \
      `conf_opt_packages gnome3 libglib2.0-dev libpanel-applet-4-dev` \
      `conf_opt_packages dbus libdbus-glib-1-dev` \
      `conf_opt_packages gstreamer libgstreamer1.0-dev` \
      `conf_opt_packages pulse libpulse-dev` \
      `conf_opt_packages indicator gobject-introspection libindicator3-dev libdbusmenu-glib-dev libdbusmenu-gtk3-dev libgirepository1.0-dev` \
      `conf_opt_packages xfce xfce4-panel-dev` \
      `conf_opt_packages manual docbook-utils xmlto`

before_script:
  - ./autogen.sh
  - |
    ./configure \
      --enable-option-checking=fatal \
      --disable-static \
      --disable-dependency-tracking \
      `conf_opt gconf` \
      `conf_opt gsettings` \
      `conf_opt xml` \
      `conf_opt gnome3` \
      `conf_opt indicator` \
      `conf_opt xfce` \
      `conf_opt mate` \
      `conf_opt dbus` \
      `conf_opt distribution` \
      `conf_opt gstreamer` \
      `conf_opt pulse` \
      `conf_opt exercises` \
      `conf_opt experimental` \
      `conf_opt manual`

script: make && make check
