sudo: required

dist: trusty

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: change

language: cpp
osx_image: xcode8.3

matrix:
  include:
    - os: linux
      compiler: gcc
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE="INDICATOR,GSTREAMER,PULSE"
        CONF_DISABLE="GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="ubuntu-zesty-plus"
    - os: linux
      compiler: gcc
      env: >
        COMPILER="gcc"
        WITH_UI="Gtk+3"
        CONF_ENABLE=""
        CONF_DISABLE="INDICATOR,GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
        DOCKER_IMAGE="mingw-gtk"
#    - os: linux
#      compiler: clang
#      env: >
#        WITH_UI="Gtk+3"
#        CONF_ENABLE="INDICATOR,GSTREAMER,PULSE"
#        CONF_DISABLE="GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
#        DOCKER_IMAGE="ubuntu-zesty-plus"
#    - os: linux
#      compiler: gcc
#      env: >
#        WITH_UI="Gtk+3"
#        CONF_ENABLE="GCONF,GNOME_CLASSIC_PANEL,INDICATOR,GSTREAMER,PULSE,COVERAGE,TRACING"
#        CONF_DISABLE=""
#        DOCKER_IMAGE="ubuntu-zesty-plus"
#    - os: linux
#      compiler: clang
#      env: >
#        WITH_UI="Gtk+3"
#        CONF_ENABLE="GCONF,GNOME_CLASSIC_PANEL,INDICATOR,GSTREAMER,PULSE,COVERAGE,TRACING"
#        CONF_DISABLE=""
#        DOCKER_IMAGE="ubuntu-zesty-plus"
#    - os: linux
#      compiler: gcc
#      env: >
#        WITH_UI="Qt5"
#        CONF_ENABLE="INDICATOR,GSTREAMER,PULSE"
#        CONF_DISABLE="GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
#        DOCKER_IMAGE="ubuntu-zesty-plus"
#    - os: linux
#      compiler: clang
#      env: >
#        WITH_UI="Qt5"
#        CONF_ENABLE="INDICATOR,GSTREAMER,PULSE"
#        CONF_DISABLE="GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
#        DOCKER_IMAGE="ubuntu-zesty-plus"
    - os: osx
      compiler: clang
      env: >
        WITH_UI="Qt5"
        CONF_ENABLE=""
        CONF_DISABLE="INDICATOR,GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF,TESTS,COVERAGE,TRACING"
#    - os: osx
#      compiler: clang
#      env: >
#        WITH_UI="Qt5"
#        CONF_ENABLE="INDICATOR,TESTS,COVERAGE,TRACING"
#        CONF_DISABLE="GSTREAMER,PULSE,GNOME_CLASSIC_PANEL,GCONF"

before_install: |
  install_osx()
  {
    # compilation with system wide gettext fails at the link stage with missing symbols...
    brew install gettext
    brew link gettext --force
    brew install qt5 python3
  }

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then install_osx; fi
  - pip3 install --user Jinja2==2.8 # required for dbus support, system (distro) wide include paths are ignored

script: |
  if [[ $DOCKER_IMAGE ]]; then
    docker run --rm \
        -v "$TRAVIS_BUILD_DIR:/workspace/source" \
        $(printenv | grep -E '^(COMPILER|WITH_UI|CONF_ENABLE|CONF_DISABLE|DOCKER_IMAGE|TRAVIS.*)=' | sed 's/^/-e /g') \
        rcaelers/workrave-build:${DOCKER_IMAGE} \
        sh -c "/workspace/source/build/travis/build.sh"
  else
     build/travis/build.sh
  fi
